version: "3.7"
services:
  postgres_flyway:
    image: postgres:14
    container_name: postgres_flyway
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: files
  storage:
    image: mcr.microsoft.com/azure-blob-storage
    container_name: storage_flyway
    restart: always
    ports:
      - "11002:11002"

volumes:
  keycloak-db-data:
  keycloak-data:

networks:
  keycloak-network: