/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.liriotech.purchaseorder.app.providers.kafka.avro.data;
@org.apache.avro.specific.AvroGenerated
public enum StatusEnum implements org.apache.avro.generic.GenericEnumSymbol<StatusEnum> {
  PENDING, PROCESSING, SCHEDULED, DONE, ERROR  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"StatusEnum\",\"namespace\":\"com.liriotech.purchaseorder.app.providers.kafka.avro.data\",\"symbols\":[\"PENDING\",\"PROCESSING\",\"SCHEDULED\",\"DONE\",\"ERROR\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
