version: "3"

services:
  localstack:
    image: localstack/localstack:0.11.2
    ports:
      - "4567-4584:4567-4584"
      - "8085:8080"
    environment:
      - SERVICES=dynamodb,s3,sqs
    volumes:
      - './.localstack:/tmp/localstack'
      #- '/var/run/docker.sock:/var/run/docker.sock'