spring:
  application:
    name: customer-dynamodb-redis-kafka-pix

amazon:
  dynamodb:
    endpoint: http://localhost:4569
  aws:
    accessKey: XXXXXXXXXXX
    secretKey: AAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    region: us-east-1

cache:
  redis:
    enable: true
    host: 'localhost'
    port: 6379
    timeout: 5000
    #defaultTimeToLive: 60
    #ediumTimeToLive: 300
    #longTimeToLive: 3600