spring:

  mongodb.embedded.version: 4.0.2
  data:
    mongodb:
      database: test
      port: 27017

  kafka:
    bootstrap-servers: kafka:9092
    properties:
      schema.registry.url: http://schema-registry:8081
      auto.create.topics.enable: true
    producer:
      topics:
        order.registration: cmd.dsr.investments.order.registration
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    consumer:
      topics:
        order.process: cmd.dsr.investments.order.registration
      auto-offset-reset: earliest
      client-id: purchase-order-client-id
      group-id: purchase-order-group-id
      specific.avro.reader: true
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer